const withOpacity = (variable) => `hsl(var(${variable}) / <alpha-value>)`

const themeColors = {
  midnight: {
    background: '#050814',
    primary: '#1E2A78',
    secondary: '#141C3A',
    accent: '#7C83FF',
    'secondary-accent': '#5D6AF2',
    'text-primary': '#E7EFFF',
    'text-secondary': '#C7D2FF',
  },
  aurora: {
    background: '#061311',
    primary: '#0F766E',
    secondary: '#12403A',
    accent: '#42DDB8',
    'secondary-accent': '#1EC6A0',
    'text-primary': '#E4FBF3',
    'text-secondary': '#BCEFE0',
  },
  sunset: {
    background: '#211016',
    primary: '#FF7043',
    secondary: '#D9486D',
    accent: '#FFB347',
    'secondary-accent': '#F973AB',
    'text-primary': '#FFE9E0',
    'text-secondary': '#FFD0C1',
  },
  slate: {
    background: '#0F141A',
    primary: '#3D4C63',
    secondary: '#1F2733',
    accent: '#6B7A93',
    'secondary-accent': '#4F5C73',
    'text-primary': '#E4EAF3',
    'text-secondary': '#C7D0DF',
  },
  light: {
    background: '#F8FAFC',
    primary: '#3B82F6',
    secondary: '#E2E8F0',
    accent: '#6366F1',
    'secondary-accent': '#94A3B8',
    'text-primary': '#1F2937',
    'text-secondary': '#475569',
  },
  dark: {
    background: '#0B1120',
    primary: '#1E293B',
    secondary: '#334155',
    accent: '#60A5FA',
    'secondary-accent': '#7C3AED',
    'text-primary': '#E2E8F0',
    'text-secondary': '#94A3B8',
  },
  cyberpunk: {
    background: '#050307',
    primary: '#0B0B23',
    secondary: '#111144',
    accent: '#00F5FF',
    'secondary-accent': '#FF3AF2',
    'text-primary': '#F8F9FF',
    'text-secondary': '#A8B0FF',
  },
  'neon-blue': {
    background: '#020012',
    primary: '#080422',
    secondary: '#0F172A',
    accent: '#0EA5E9',
    'secondary-accent': '#2563EB',
    'text-primary': '#E7F2FF',
    'text-secondary': '#A3C3FF',
  },
  'purple-glow': {
    background: '#12051C',
    primary: '#1C0D2A',
    secondary: '#3E1D5F',
    accent: '#A855F7',
    'secondary-accent': '#F472B6',
    'text-primary': '#F3E8FF',
    'text-secondary': '#D9B4FF',
  },
}

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    'animate-pulse',
    'animate-[pulse_2s_cubic-bezier(0.4,0,0.6,1)_infinite]',
    {
      pattern: /animate-(in|out)/,
    },
    {
      pattern: /framer-motion-/,
    },
  ],
  theme: {
    extend: {
      colors: {
        border: withOpacity('--border'),
        input: withOpacity('--input'),
        ring: withOpacity('--ring'),
        background: withOpacity('--background'),
        foreground: withOpacity('--foreground'),
        card: withOpacity('--card'),
        'card-foreground': withOpacity('--card-foreground'),
        popover: withOpacity('--popover'),
        'popover-foreground': withOpacity('--popover-foreground'),
        primary: withOpacity('--primary'),
        'primary-foreground': withOpacity('--primary-foreground'),
        secondary: withOpacity('--secondary'),
        'secondary-foreground': withOpacity('--secondary-foreground'),
        muted: withOpacity('--muted'),
        'muted-foreground': withOpacity('--muted-foreground'),
        accent: withOpacity('--accent'),
        'accent-foreground': withOpacity('--accent-foreground'),
        destructive: withOpacity('--destructive'),
        'destructive-foreground': withOpacity('--destructive-foreground'),
        surface: {
          DEFAULT: withOpacity('--surface-1'),
          muted: withOpacity('--surface-2'),
          accent: withOpacity('--surface-3'),
        },
        overlay: withOpacity('--overlay'),
        ...themeColors,
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      boxShadow: {
        glass: '0 18px 45px rgba(15, 23, 42, 0.18)',
        glow: '0 0 25px rgba(99, 102, 241, 0.35)',
      },
      animation: {
        'pulse-soft': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
